### ISSUE TITLE
thanm所需参数已修改

### ISSUE THREAD

**Issue by xitieshiz2** [RUEEE/re_thtk_gui#1]
[这个commit](https://github.com/thpatch/thtk/commit/8374c50ad56420531fdd5904c6e32dde55b514ac)更新了thanm的命令行参数要求，导致GUI失效

**Comment by RUEEE** [comment]
找到 config/command.ini
然后在anm的部分按照需求加入 @gameVer 参数
这玩意当时是瞎搓的一个parser所以比较丑陋，不过应该没问题
考虑到th19正式版快到了所以先这样简单用着吧(
到时候再更新了
